name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Bygger och pushar när kod pushas till main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t zocomchristoffer/my-server:latest .

      - name: Push Docker image
        run: |
          docker push zocomchristoffer/my-server:latest
